### ISSUE TITLE
Refactor the storage of Packages on the WebServices in a Database

### ISSUE THREAD

**Issue by qalldredge** [gcentral/Website#1]
Refactor the storage of Packages on the WebServices in a Database instead of a file as it is now. I think using SQLite would be a good idea since it doesn’t involve complex infrastructure with the need to install a database server.

**Comment by francois-normandin** [comment]
I'm quoting the rest of the quote attributed to @matthiasbaudot on GCentral's collaboration page:

> The WebServices will need to be modified to go look for packages in that database instead of looking at the Repo global variable.

**Comment by francois-normandin** [comment]
I suggest this should be refactored as an interface, so that SQLite is one possible implementation and we use this as a demo of the addition of interfaces in the LabVIEW language.
