### ISSUE TITLE
Implement a Configuration File

### ISSUE THREAD

**Issue by qalldredge** [gcentral/Website#2]
Implement a Configuration File for the Web Services where we can specify the repositories to be fetched (GPM, VIPM, NIPM). Right now, there is only one GPM repo and 2 VIPM repos. When we will add NIPM, it will be important to be able to specify the feeds in a config file rather than rebuilding the WebServices when a new feed needs to be added.

**Comment by chrisb2244** [comment]
Quentin, Francois, I'd be happy to take a look at this issue if nobody else is working on it. Before I go heading off in the wrong direction, perhaps I can ask a couple of questions:

1. Do you want this to be a single file for all repositories, or split by type (I think perhaps a single file is clearer)
2. Would you plan on putting anything else in this file? (Perhaps not?)
3. Do you have a desired file type/layout/format, or would anything that associates a Name, URL and Type be appropriate?
4. Are there any other pieces of information you'd particularly like associating with a Repository?
5. Would you plan on checking this file every 30s in the WS_Main timeout case?
