### ISSUE TITLE
Upcompile GCentral to LabVIEW 2020 Community / NXG

### ISSUE THREAD

**Issue by ChrisCilinoGC** [gcentral/Website#25]
In order to invite as many people as possible to contribute to GCentral, we should use the community editions.

**Comment by ChrisCilinoGC** [comment]
This is a duplicate of https://github.com/gcentral/Website/issues/24

**Comment by francois-normandin** [comment]
@ChrisCilinoGC it is not a duplicate, it is actually the translation of the user story into concrete actions. Check out the workflow recommendation here: https://github.com/gcentral/Website/wiki/Contribution-Guidelines

I recommend we close the user stories with a reference to the actual enhancements they were translated into.

**Comment by ChrisCilinoGC** [comment]
Oh that's a great call @francois-normandin !
