### ISSUE TITLE
Move the collaboration instructions to the readme \ wiki of this GItHub Repo

### ISSUE THREAD

**Issue by ChrisCilinoGC** [gcentral/Website#26]

**Comment by francois-normandin** [comment]
Working on the Contribution Guidelines.
https://github.com/gcentral/Website/wiki/Contribution-Guidelines

Still need to transfer the How-To part of GCentral to an equivalent wiki page.
https://www.gcentral.org/support/collaborate ==> wiki

Special branch to upload screenshots for the wiki: https://github.com/gcentral/Website/tree/feature/wiki/wiki/images

**Comment by qalldredge** [comment]
All moved over. See [Setup the Development Environment](https://github.com/gcentral/Website/wiki/Setup-the-Development-Environment).
