### ISSUE TITLE
Package descriptions show raw formatting tags

### ISSUE THREAD

**Issue by JKSH** [gcentral/Website#67]
`<b>...</b>` tags are displayed as plain text which remains unformatted on the GCentral website. In contrast, VIPM hides the tags and renders the text **in bold**.

Example: https://demo.studiobods.com/GCentral_Indexer/PackageDetails.html?Name=acrome_robotics_lib_1_dof_helicopter_software

**Comment by negentropicdev** [comment]
Hello @JKSH you're linking to an old demo site that was a prototype of the first version of the website. Our current test site is at https://test.gcentral.org and we do interpret the html in package descriptions: https://test.gcentral.org/package/366

**Comment by JKSH** [comment]
> you're linking to an old demo site that was a prototype of the first version of the website. Our current test site is at https://test.gcentral.org

Ah, I see. In that case, feel free to close this ticket.

Note 1: I started looking at gcentral.org because this thread asked for beta testers: https://lavag.org/topic/21912-looking-for-beta-testers/ (However, it doesn't link to the test site)

Note 2: The example package (1-DOF Helicopter Software) is at the top of the package list at the current version of gcentral.org, but I can't find it in the new test site.

**Comment by negentropicdev** [comment]
Yes we need to finish updating the indexer to the new site and that includes bringing in package repositories that stopped working for some reason but we've transitioned to a new platform so we have to start over with it anyway.

What brought you to the studiobods site?

**Comment by JKSH** [comment]
> What brought you to the studiobods site?

I read https://lavag.org/topic/21912-looking-for-beta-testers/ so I went to the current GCentral website (https://www.gcentral.org/). I scrolled down to the "Discover Packages" section, picked a package, and clicked "Show Package Details". That's what brought me to the studiobods site.

**Comment by negentropicdev** [comment]
Ahh got it, thanks! I'm going to go ahead and close this up now.
