### ISSUE TITLE
Show the license that the package is published under

### ISSUE THREAD

**Issue by JKSH** [gcentral/Website#69]
For example, https://www.vipm.io/package/openg.org_lib_openg_toolkit/ shows that the OpenG Toolkit is licenced under _"BSD, LGPL"_. The corresponding entry at https://test.gcentral.org/package/353 should do the same.

**Comment by francois-normandin** [comment]
Licensed under MIT.
pull request #70

**Comment by chrisb2244** [comment]
I think this has been closed a little early - the issue/request isn't that GCentral declare its own license, but that it display the licenses chosen by package creators.

**Comment by francois-normandin** [comment]
You're correct. I was responding to a LAVAG post which I incorrectly assumed was this issue.
(The website repo didn't have license, this is now resolved)

Edit: I see why I assumed it was the same issue... both were [posts](https://lavag.org/topic/21912-looking-for-beta-testers/?tab=comments#comment-135328) from JKSH :-)
